config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  get "user", to: "pages#user"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :categories
  resources :books do
    resources :requests
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Book.ransack(params[:q])
    @books = @query.result(distinct: true)
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class: "d-flex") do |f| %>
    <%= f.search_field :title_or_author_or_category_name_i_cont_any, placeholder: "Search by Title, Author and Category", class: "form-control me-2 search-bar-main" %>
    <%= f.submit "Search", class: "btn btn-dark search-bar-btn" %>
<% end %>

app/views/search/index.html.erb
<h1 class="text-center"><%= pluralize(@books.count, "result") %> found</h1>
<br />
<%= render "search/form" %>
<br />
<%= link_to "Back to books", books_path %>
<br />
<br />
<div class="container">
    <div class="category-row container">
        <%= sort_link(@query, :title, "", default_order: :asc) %>
            <div class="row tm-catalog-item-list">
                <% @books.each do |book| %>
                    <div class="col-lg-3 col-md-4 col-sm-6 tm-catalog-item">
                        <% if book.image.attached? %> 
                            <%= link_to image_tag(book.image_as_thumbnail, class: "book-thumbnail"), book %>
                        <% else %>
                            <div class="no-image-thumbnail-div">
                                <%= link_to book.title, book, class: "no-image-thumbnail" %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
            </div>
    </div>
</div>