config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  get "user", to: "pages#user"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :categories
  resources :books do
    resources :requests
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/book.rb
class Book < ApplicationRecord
    validates :category_id, presence: true
    validates :title, presence: true, length: { minimum: 1, maximum: 50 }
    validates :description, presence: true, length: { minimum: 50, maximum: 1000 }
    belongs_to :category
    belongs_to :user
    has_many :requests, dependent: :destroy
    has_one_attached :image, dependent: :destroy
    has_noticed_notifications model_name: "Notification"
    has_many :notifications, through: :user, dependent: :destroy

    def image_as_thumbnail
        return unless image.content_type.in?(%w[image/jpeg image/png])
            image.variant(resize_to_limit: [300,300]).processed
        end        
    end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit ]
  before_action :set_categories

  # GET /books or /books.json
  def index
    @books = Book.all.order("created_at DESC")
  end

  # GET /books/1 or /books/1.json
  def show
    @book = Book.find(params[:id])
    @requests = @book.requests.order("created_at DESC")
    mark_notifications_as_read
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    @book.category_id = params[:category_id]
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :image, :description, :author, :category_id)
    end

    def set_categories
      @categories = Category.all.order(:name)      
    end

    def mark_notifications_as_read
      notifications_to_mark_as_read = @book.notifications_as_book.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">

  <div class="row">
    <div class="col-md-4">
      <% if book.image.attached? %> 
        <%= link_to image_tag(book.image_as_thumbnail, class: "book-showpage"), book %>
      <% else %>
        <div class="no-image-show-div">
          <p class="no-image-show">We're still looking for a perfect image of this book.</p>
        </div>
      <% end %>
    </div>

    <div class="col-md-8">
      <h2>
        <strong><%= book.title %></strong>
      </h2>

      <p>
        <strong>(<%= link_to book.category.name, book.category %>)</strong>        
      </p>

      <p>
      posted by <strong><%= book.user.user_name %></strong>
      </p>

      <p>
        <strong>Description:</strong>
        <%= book.description %>
      </p>

      <p>
        <strong><%= book.author %></strong>
      </p>
    </div>

</div>

app/views/books/_form.html.erb
<!DOCTYPE html>
<html lang="en">
  <body class="body-form">
    <div class="tm-page-wrap mx-auto">
      <div class="position-relative">
        <div class="form-body">
          <div class="row">
            <div class="form-holder">
              <div class="form-content">
                <div class="form-items">
                  <h3>Spread the knowledge</h3>
                  <%= form_with(model: book) do |form| %>
                    <% if book.errors.any? %>
                      <div style="color: red">
                        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

                        <ul>
                          <% book.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="col-md-12 form-styling">
                      <%= form.text_field :title, class: "form-control", placeholder: "Book name" %>
                    </div>

                    <div class="col-md-12 form-styling-btn">
                      <%= form.file_field :image %>
                    </div>

                    <div class="col-md-12 form-styling">
                      <%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]}), class: "form-select mt-3" %>
                    </div>

                    <div class="col-md-12 form-styling">
                      <%= form.text_area :description, class: "form-control", placeholder: "Enter the description"%>
                    </div>

                    <div class="col-md-12 form-styling">
                      <%= form.text_field :author, class: "form-control", placeholder: "Author" %>
                    </div>

                    <div class="col-md-12 form-styling">
                      <%= form.check_box :confirmation %>
                      <%= form.label :confirmation, "I confirm that all data are correct" %>
                    </div>

                    <div class="form-styling-btn">
                      <%= form.submit %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      (function () {
        "use strict";
        const forms = document.querySelectorAll(".requires-validation");
        Array.from(forms).forEach(function (form) {
          form.addEventListener(
            "submit",
            function (event) {
              if (!form.checkValidity()) {
                event.preventDefault();
                event.stopPropagation();
              }

              form.classList.add("was-validated");
            },
            false
          );
        });
      })();
    </script>
  </body>
</html>

app/views/books/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <body class="body-form">
    <div class="tm-page-wrap mx-auto">
      <div class="position-relative">
        <div class="form-body">
          <div class="row">
            <div class="form-holder">
              <div class="form-content">
                <div class="form-items">
                  <h3>Edit Book</h3>
                  <%= form_with(model: @book, :html => { :multipart => true }) do |form| %>
                    <% if @book.errors.any? %>
                      <div style="color: red">
                        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

                        <ul>
                          <% @book.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="col-md-12 form-styling">
                      <%= form.text_field :title, class: "form-control", placeholder: "Book name" %>
                    </div>

                    <div class="col-md-12 form-styling-btn">
                      <%= form.file_field :image, placeholder: "Upload file" %>
                    </div>

                    <div class="col-md-12 form-styling">
                      <%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]}), class: "form-select mt-3" %>
                    </div>

                    <div class="col-md-12 form-styling">
                      <%= form.text_area :description, class: "form-control", placeholder: "Enter the description"%>
                    </div>

                    <div class="col-md-12 form-styling">
                      <%= form.text_field :author, class: "form-control", placeholder: "Author" %>
                    </div>

                    <div class="col-md-12 form-styling">
                      <%= form.check_box :confirmation %>
                      <%= form.label :confirmation, "I confirm that all data are correct" %>
                    </div>

                    <div class="form-styling-btn">
                      <%= form.submit %>
                    </div>
                  <% end %>
                  <div>
                    <%= link_to "Show this book", @book %> |
                    <%= link_to "Back to books", books_path %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      (function () {
        "use strict";
        const forms = document.querySelectorAll(".requires-validation");
        Array.from(forms).forEach(function (form) {
          form.addEventListener(
            "submit",
            function (event) {
              if (!form.checkValidity()) {
                event.preventDefault();
                event.stopPropagation();
              }

              form.classList.add("was-validated");
            },
            false
          );
        });
      })();
    </script>
  </body>
</html>

app/views/books/index.html.erb
<div class="row">
  <div class="col-12">
    <h2 class="tm-page-title mb-4"
      style="font-family: 'League Script', cursive;
        font-size: 4rem;
        -webkit-text-stroke: 2px black;
        padding-left: 1rem;">
      Books for donation
    </h2>
  </div>
</div>

<br />
<br />

<div class="row">
  <div class="col-md-4">
    <%= link_to "Categories", categories_path, class: "btn btn-dark text-center mb-3 category-btn" %>
  </div>
  <div class="col-md-8">
    <%= render "search/form" %>
  </div>
</div>

<br />


<div id="books">
  <% if @books.count == 0 %>

    <h1>There are no books currently.</h1>

  <% else %>
    <div class="row tm-catalog-item-list">
      <% @books.each do |book| %>
        <div class="col-lg-3 col-md-4 col-sm-6 tm-catalog-item">
          <% if book.image.attached? %> 
            <%= link_to image_tag(book.image_as_thumbnail, class: "book-thumbnail"), book %>
          <% else %>
            <div class="no-image-thumbnail-div">
              <%= link_to book.title, book, class: "no-image-thumbnail" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<%= render "form", book: @book %>
<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<%= render @book %>

<br>

<div class="row container">

  <div class="col-md-6">
    <%= link_to "Back to books", books_path %>
    <% if user_signed_in? %>
      <% if @book.user_id == current_user.id %>
        | <%= link_to "Edit this book", edit_book_path(@book) %>
        <% if current_user.moderator? %>
          <%= button_to "Destroy this book", @book, method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-6">  
      <% if user_signed_in? %>
        <% if Request.where(book_id: @book.id).count < 5 %>
          <%= render "requests/form", book: @book %>
        <% end %>
      <% end %>
  </div>

  <br />

  <div class="col-md-12 request-index">
    <% if @book.user_id == current_user.id || current_user.moderator? || current_user.admin? %>
    <h2>There are <%= pluralize(@requests.count, "request") %> for this book.</h2>
      <% @requests.each do |request| %>
        <%= render "requests/request", book: @book, request: request %>
      <% end %>
    <% end %>
  </div>

</div>