config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  get "user", to: "pages#user"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :categories
  resources :books do
    resources :requests
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :books
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <h2>
    <strong><%= link_to category.name, category %></strong>
  </h2>

  <% if category.books.count == 0 %>

    <h1>There are no books currently in this category.</h1>

  <% else %>
    <div class="row tm-catalog-item-list">
      <% category.books.each do |book| %>
        <div class="col-lg-3 col-md-4 col-sm-6 tm-catalog-item">
          <% if book.image.attached? %> 
            <%= link_to image_tag(book.image_as_thumbnail, class: "book-thumbnail"), book %>
          <% else %>
            <div class="no-image-thumbnail-div">
              <%= link_to book.title, book, class: "no-image-thumbnail" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

</div>

app/views/categories/_form.html.erb
<!DOCTYPE html>
<html lang="en">
  <body class="body-form">
    <div class="tm-page-wrap mx-auto">
      <div class="position-relative">
        <div class="form-body">
          <div class="row">
            <div class="form-holder">
              <div class="form-content">
                <div class="form-items">
                  <h3>Bring in a new family of books</h3>
                    <%= form_with(model: category) do |form| %>
                      <% if category.errors.any? %>
                        <div style="color: red">
                          <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

                          <ul>
                            <% category.errors.each do |error| %>
                              <li><%= error.full_message %></li>
                            <% end %>
                          </ul>
                        </div>
                      <% end %>

                    <div class="col-md-12 form-styling">
                      <%= form.text_field :title, class: "form-control", placeholder: "Book name" %>
                    </div>
                    
                    <div class="form-styling-btn">
                      <%= form.submit %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      (function () {
        "use strict";
        const forms = document.querySelectorAll(".requires-validation");
        Array.from(forms).forEach(function (form) {
          form.addEventListener(
            "submit",
            function (event) {
              if (!form.checkValidity()) {
                event.preventDefault();
                event.stopPropagation();
              }

              form.classList.add("was-validated");
            },
            false
          );
        });
      })();
    </script>
  </body>
</html>

app/views/categories/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <body class="body-form">
    <div class="tm-page-wrap mx-auto">
      <div class="position-relative">
        <div class="form-body">
          <div class="row">
            <div class="form-holder">
              <div class="form-content">
                <div class="form-items">
                  <h3>Edit Category</h3>
                    <%= form_with(model: @category, :html => { :multipart => true }) do |form| %>
                      <% if @category.errors.any? %>
                        <div style="color: red">
                          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

                          <ul>
                            <% @category.errors.each do |error| %>
                              <li><%= error.full_message %></li>
                            <% end %>
                          </ul>
                        </div>
                      <% end %>

                    <div class="col-md-12 form-styling">
                      <%= form.text_field :title, class: "form-control", placeholder: "Category name" %>
                    </div>
                    
                    <div class="form-styling-btn">
                      <%= form.submit %>
                    </div>
                  <% end %>
                  <div>
                    <%= link_to "Show this category", @category %> |
                    <%= link_to "Back to categories", categories_path %>
                  </div>                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      (function () {
        "use strict";
        const forms = document.querySelectorAll(".requires-validation");
        Array.from(forms).forEach(function (form) {
          form.addEventListener(
            "submit",
            function (event) {
              if (!form.checkValidity()) {
                event.preventDefault();
                event.stopPropagation();
              }

              form.classList.add("was-validated");
            },
            false
          );
        });
      })();
    </script>
  </body>
</html>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><strong>Categories</strong></h1>
<%= link_to "Back to books", books_path %>
<% if current_user %>
  <% if current_user.admin? || current_user.moderator? %>
    <%= link_to "New category", new_category_path %>
  <% end %>
<% end %>

<div id="categories" class="container">
  <% @categories.each do |category| %>
    <div id="<%= dom_id category %>">
      <h2>
        <strong><%= link_to category.name, category %></strong>
      </h2>

      <% if category.books.count == 0 %>
        <h4>There are no books currently in this category.</h4>
      <% else %>
        <div class="row tm-catalog-item-list">
          <% category.books.each do |book| %>
            <div class="col-lg-3 col-md-4 col-sm-6 tm-catalog-item">
              <% if book.image.attached? %> 
                <%= link_to image_tag(book.image_as_thumbnail, class: "book-thumbnail"), book %>
              <% else %>
                <div class="no-image-thumbnail-div">
                  <%= link_to book.title, book, class: "no-image-thumbnail" %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
      <br />
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>
<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Back to categories", categories_path %>

  <% if user_signed_in? %>
    <% if current_user.admin? || current_user.moderator? %>
      | <%= link_to "Edit this category", edit_category_path(@category) %>
      <%= button_to "Destroy this category", @category, data: { confirm: "Are you sure?" }, method: :delete %>
    <% end %>
  <% end %>
</div>