config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  get "user", to: "pages#user"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :categories
  resources :books do
    resources :requests
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/_alerts.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<div class="alert-container">
    <% if notice %>
        <div class="alert alert-success d-flex align-items-center alert-message" role="alert">
            <svg class="bi flex-shrink-0 me-2 alert-symbol" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div>
                <%= notice %>
            </div>
        </div>
    <% elsif  alert %>
        <div class="alert alert-danger d-flex align-items-center alert-message" role="alert">
            <svg class="bi flex-shrink-0 me-2 alert-symbol" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
                <%= alert %>
            </div>
        </div>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="position-relative tm-site-header">
  <div class="container-fluid position-relative">
    <div class="row">
      <div class="col-7 col-md-8">

        <%= render "user/session_manager" %>
        
      </div>      
      <div class="col-5 col-md-4 ml-auto mr-0">
        <nav class="navbar navbar-expand-lg mr-0 ml-auto" id="tm-main-nav">
          <button class="navbar-toggler tm-bg-black py-2 px-3 mr-0 ml-auto collapsed" type="button" data-toggle="collapse" data-target="#navbar-nav" aria-controls="navbar-nav" aria-expanded="false" aria-label="Toggle navigation">
              <span>
                  <i class="fas fa-bars tm-menu-closed-icon"></i>
                  <i class="fas fa-times tm-menu-opened-icon"></i>
              </span>
          </button>
          <div class="collapse navbar-collapse tm-nav" id="navbar-nav">
            <ul class="navbar-nav text-uppercase navbar-right">     

              <li>
                <%= render "layouts/notifications" %>
              </li>

              <li class="nav-item">
                  <%= link_to "Need", books_path, class: "nav-link tm-nav-link" %>
              </li>
              
              <li class="nav-item">
                <%= link_to "Give", new_book_path, class: "nav-link tm-nav-link" %>
              </li>
            </ul>
          </div>
        </nav>

        <%= render 'layouts/alerts' %>
      
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notification.html.erb
<li class="dropdown-item">
    <%= link_to notification.to_notification.message, notification.to_notification.url %>
</li>

app/views/layouts/_notifications.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <span class="badge rounded-pill bg-black">
        <%= @unread.count >= 9 ? "9+" : @unread.count %> <i class="bi bi-bell-fill"></i>
      </span>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <% @unread.each do |notification| %>
        <%= render 'layouts/notification', notification: notification %>
      <% end %>
      <% if @read.count > 0 && @unread.count > 0 %>
        <li>
          <hr class="dropdown-divider">
        </li>
      <% elsif @read.count + @unread.count == 0 %>
        <li class="dropdown-item">
          No notifications yet.
        </li>
      <% end %>
      <% @read.each do |notification| %>
        <%= render 'layouts/notification', notification: notification %>
      <% end %>
    </ul>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Donation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=League+Script&display=swap" rel="stylesheet"/>
  </head>

  <body>
    
    <header>
      <%= render 'layouts/navbar' %>
    </header>  
  
    
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  
  </body>
</html>